name: CinemaRenderTest

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup OpenGL
      uses: openrndr/setup-opengl@v1.1
    - name: Install dependencies
      run: |
        python setup.py install
    - name: Run the tests
      run: |
        python -m unittest testing/CinemaRenderTest.py
